version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/api/static/
      - media_volume:/api/media/
    depends_on:
      - api
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: todo_api
    command: gunicorn home.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/api
      - /tmp/app/mysqld:/run/mysqld
      - static_volume:/api/static/
      - media_volume:/api/media/
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.38
    container_name: mysql_db
    healthcheck:
      test: ["CMD", "mysqladmin","ping", "-h", "sql.freedb.tech"]
      interval: 5s
      timeout: 5s
      retries: 2
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql


volumes:
  static_volume:
  media_volume: