# Generated by Django 5.0.6 on 2024-07-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
